### ISSUE TITLE
Bad commit message history

### ISSUE THREAD

**Issue by kilasuit** [Azure/cloud-rolesandops#49]
This repo doesn't show good commit message history which is detrimental to anyone coming to this repo.

Git allows you to rewrite commit messages, which I would not only ask but demand you as a team go back and do, so that they are more informational than they are now, because this repo currently looks like it is being managed by really lazy individuals and doesn't look right when you compare it to any other Azure repository. Your managers should have picked this up, not a member of the community.

So please do the right thing and rebuild the history with usable commit messages & start making usable commit messages going forward @Kaspanitz

**Comment by Kaspanitz** [comment]
Thank you for your feedback. We have reset the commit history now as it was just part of the initial release. We will be sure to provide meaningful messages with our future commits.
