### ISSUE TITLE
Bug: Cannot import basic workbook - Request size is too large

### ISSUE THREAD

**Issue by jonathan-vella** [Azure/cloud-rolesandops#52]
Importing the [basic workbook](https://github.com/Azure/cloud-rolesandops/blob/main/basic%20workbook/Planning%20Guide%20for%20Cloud%20Roles%20and%20Operations%20Management%20v0.91b.json) either by using the "deploy to azure" button or pasting the json content results in {"Errors":["Request size is too large"]}.

The updateable workbook can be imported.

**Comment by Kaspanitz** [comment]
@jonathan-vella Thank you for raising this issue. The cause is due to the volume of content in the basic workbook. We will work on a solution, e.g. splitting content into a reference workbook, or using an external source.

**Comment by Kaspanitz** [comment]
A workaround for the request size issue is to save the workbook to storage i.e., https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-bring-your-own-storage

@jonathan-vella
