### ISSUE TITLE
Agree to the Terms to create the resource

### ISSUE THREAD

**Issue by frehnejc** [Azure/cloud-rolesandops#54]
On trying to deploy to Azure received this error:
![image](https://user-images.githubusercontent.com/26272784/186843896-e2b55639-0df5-448f-956e-81f2f7f9f4d2.png)

**Comment by NWiddup** [comment]
Hi @frehnejc, Thanks for raising this issue! I've had a look and it appears that there's an issue with the casing of the Resource's Type. 'microsoft.insights/workbooks' errors, and "Microsoft.Insights/workbooks" does not. I've just fixed it & will get the updates merged shortly. Thanks!
